/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f7f9fb',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-container': '#54647a',
        'on-tertiary-fixed': '#001a42',
        'on-background': '#191c1e',
        'on-tertiary-fixed-variant': '#004395',
        'on-primary-container': '#7c839b',
        'inverse-primary': '#bec6e0',
        surface: '#f7f9fb',
        'tertiary-container': '#001a42',
        'on-surface-variant': '#45464d',
        'primary-fixed': '#dae2fd',
        'surface-container-highest': '#e0e3e5',
        'tertiary-fixed': '#d8e2ff',
        'secondary-fixed': '#d3e4fe',
        'surface-variant': '#e0e3e5',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#131b2e',
        'primary-container': '#131b2e',
        'surface-container': '#eceef0',
        'on-primary': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'on-primary-fixed-variant': '#3f465c',
        'surface-dim': '#d8dadc',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#3980f4',
        'error-container': '#ffdad6',
        'secondary-container': '#d0e1fb',
        'tertiary-fixed-dim': '#adc6ff',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#b7c8e1',
        secondary: '#505f76',
        outline: '#76777d',
        primary: '#000000',
        'surface-container-high': '#e6e8ea',
        'on-error-container': '#93000a',
        'surface-bright': '#f7f9fb',
        'on-surface': '#191c1e',
        error: '#ba1a1a',
        'primary-fixed-dim': '#bec6e0',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        tertiary: '#000000',
        'surface-tint': '#565e74',
        'on-secondary-fixed-variant': '#38485d',
        'on-secondary': '#ffffff',
        'outline-variant': '#c6c6cd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        margin: '16px',
        xl: '24px',
        unit: '4px',
        md: '12px',
        gutter: '12px',
        sm: '8px',
        xs: '4px',
        lg: '16px',
      },
      fontFamily: {
        'label-md': ['Geist Sans', 'sans-serif'],
        'label-xs': ['Geist Sans', 'sans-serif'],
        'headline-lg': ['Geist Sans', 'sans-serif'],
        'body-md': ['Geist Sans', 'sans-serif'],
        'body-sm': ['Geist Sans', 'sans-serif'],
        'headline-md': ['Geist Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-xs': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'headline-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
